### ISSUE TITLE
Cloud SDK pagination

### ISSUE THREAD

**Issue by jaredm-ibm** [IBM-Cloud/ibm-cloud-sdk-ruby#10]
Some API collections return with total_counts others don't. To remove any application logic in the plugin we are going to fetch all results bundle them up and then pass them as a single response to the client all is requested.

**Comment by agrare** [comment]
We could also use `enum_for` and blocks to fetch in pages and yield one at a time.  We do this over in [this project](https://github.com/RedHatInsights/topological_inventory-orchestrator/blob/master/lib/topological_inventory/orchestrator/api.rb#L76-L94) an makes it easy for the caller just use all the normal `#select`/`#collect`/`#reject`/etc... methods and not have to worry about paging

**Comment by Fryguy** [comment]
:+1: for an enumerator as the caller can then bail early (with calls like `.first(5)`, for example) and the enumerator won't continue to fetch pages.

**Comment by jaredm-ibm** [comment]
Yes it is a great idea and have it working. Just going through and making touch ups.
