### ISSUE TITLE
SDK is now broken since it tries to import a non existing file

### ISSUE THREAD

**Issue by Real-Omar-Afifi** [IBM-Cloud/ibm-cloud-sdk-ruby#23]
https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/blob/master/lib/ibm/cloud/sdk/vpc/instances.rb#L7

This file does not exist, we either need to move instance_profiles.rb  from the vpc dir to the instance dir and rename it profiles or require instance_profiles instead of instance/profiles

**Comment by Real-Omar-Afifi** [comment]
@jaredm-ibm ^

**Comment by agrare** [comment]
Fixed by https://github.com/IBM-Cloud/ibm-cloud-sdk-ruby/pull/24

**Comment by jaredm-ibm** [comment]
I noticed that this morning. I've fixed it and Adam has pulled it. Doing a git pull in master should fix the issue.
